export enum PhaseRider {
  NOT_READY = 'NOT_READY',
  READY_TO_RIDE = 'READY_TO_RIDE',
  NEED_A_RIDE = 'NEED_A_RIDE',
  GET_A_RIDE = 'GET_A_RIDE',
  PICK_UP_CUSTOMER = 'PICK_UP_CUSTOMER',
  GO_TO_DESTINATION = 'GO_TO_DESTINATION',
  FINISH_RIDE = 'FINISH_RIDE'
}
